development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: 61074d57b989c75a1@ec2-54-146-105-205.compute-1.amazonaws.com:24369
  channel_prefix: Columbia_Chat_production
